name: Generate QR Code and Download

on:
  push:
    branches:
      - main  # Modify this to your main branch name
  pull_request:
    branches:
      - main  # Modify this to your main branch name

jobs:
  generate_qr_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
      
      - name: Generate QR Code
        run: |
          python QR.py "Hello, QR Code!"
          mv qrcode.png $HOME/Desktop/qrcode.png  # Move the generated QR code to the desktop
        working-directory: ${{ github.workspace }}

      - name: Upload QR Code
        uses: actions/upload-artifact@v2
        with:
          name: QR Code
          path: $HOME/Desktop/qrcode.png
